import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home page | My Shop', template: '%s | My Shop' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={inter.header}>
          <nav>
            <div>
              <Link href="/">Home</Link>
            </div>

            <Link href="/products" data-test-id="products-link">
              Products
            </Link>

            <div>
              <Link href="/About">About</Link>
            </div>

            <div>
              <Link href="/Cart">Cart</Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
